---
version: '3'
services:
  hsp-fo-discovery:
    image: 'hsp/hsp-fo-indexer:0.10.0-SNAPSHOT'
    build:
      context: .
      args:
        - 'SOLR_HOST=http://solr:8983/solr'
  solr:
    image: solr:8
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - hsp
volumes:
  data:
