#sonar.projectKey=GroupID:ArtefaktID
#sonar.projectName=SRU-Service
#sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.libraries=/home/jenkins/.m2/repository/**/*.jar
sonar.java.test.libraries=/home/jenkins/.m2/repository/**/*.jar
#sonar.java.libraries.empty=true
sonar.dynamicAnalysis=reuseReports
#sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/test-reports
#sonar.sourceEncoding=UTF-8
#sonar.projectDescription=
#sonar.links.homepage=
#sonar.links.ci=
#sonar.links.issue=
#sonar.links.scm=
#sonar.exclusions=
#sonar.test.exclusions=
#sonar.java.libraries=
#sonar.jdbc.dialect=mssql
#sonar.language=java
sonar.junit.reportsPath=target/test-reports
#sonar.verbose=true
#sonar.modules=activitystreams-hsp,tei-jaxb
#activitystreams-hsp.sonar.sources=src/main/java
#activitystreams-hsp.sonar.tests=src/test/java
#activitystreams-hsp.sonar.java.binaries=target/classes
#activitystreams-hsp.sonar.java.libraries=target/**/WEB-INF/lib
#activitystreams-hsp.sonar.java.test.libraries=target/**/WEB-INF/lib

sonar.projectKey=staatsbibliothek-berlin.hsp:hsp-fo-indexer:public
sonar.projectVersion=1.6.0
