#!/bin/sh

#
# MIT License
#
# Copyright (c) 2023 Staatsbibliothek zu Berlin - Preußischer Kulturbesitz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#

set -e


case "$1" in
    configure)
        # create a [[artifactId]] group and user
        if ! getent passwd [[artifactId]] >/dev/null 2>&1; then
                addgroup --system --gid 252 [[artifactId]]
                adduser --system --uid 252 --gid 252 [[artifactId]]
        fi
        
        mkdir -p /data/log/[[artifactId]] && chown -R [[artifactId]]:[[artifactId]] /data/log/[[artifactId]]
        mkdir -p /etc/SBB/[[artifactId]] && chown -R [[artifactId]]:[[artifactId]] /etc/SBB/[[artifactId]]
        mkdir -p /usr/local/SBB/usr/local/[[artifactId]] && chown -R [[artifactId]]:[[artifactId]] /usr/local/SBB/usr/local/[[artifactId]]
        
        rm -f /data/log/hsp-fo-indexer/hsp-fo-indexer.warn.log*
    ;;


    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Start [[artifactId]]

update-rc.d [[artifactId]] defaults 85
service [[artifactId]] stop >/dev/null 2>&1 || true
service [[artifactId]] start || true

exit 0

